language: ruby
rvm:
  - rvm 2.2.7
  - rvm 2.3.4

before_install:
  - sudo apt-get install postgresql-server-dev-9.1 libpq-dev

before_script:
  - psql -c 'create database warm_transfer_sinatra_test;' -U postgres

install:
  - bundle
